SET IDENTITY_INSERT [dbo].[Categories] ON
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (1, N'Service sector')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (2, N'Sale, purchase')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (3, N'Hotel and restaurant business, tourism')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (4, N'Workers specialty, production')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (5, N'IT, computers, internet')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (6, N'Administration, middle management')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (7, N'Logistics, warehouse, foreign trade')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (8, N'Accounting, audit')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (9, N'Transport, autobusiness')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (10, N'Secretariat, office work, AGV')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (11, N'Marketing, advertising, PR')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (12, N'Construction, architecture')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (13, N'Telecommunications and communications')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (14, N'Finance, Bank')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (15, N'Design, creativity')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (16, N'Education, science')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (17, N'Beauty, fitness, sports')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (18, N'Medicine, pharmaceuticals')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (19, N'Media, publishing, printing')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (20, N'Personnel Management, HR')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (21, N'Top management, top management')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (22, N'Facebook API')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (23, N'Security')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (24, N'Jurisprudence')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (25, N'Agriculture, agribusiness')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (26, N'Real estate')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (27, N'Culture, music, show business')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (28, N'Insurance')
INSERT INTO [dbo].[Categories] ([ID], [Name]) VALUES (29, N'Sales Manager')
SET IDENTITY_INSERT [dbo].[Categories] OFF
